#!/usr/bin/env python3
"""Generate and verify the Random Archive route list embedded in wiki.js.

wiki.js keeps a generated block between two marker comments. This tool rewrites
that block with the current list of public routes (every HTML page except the
404 recovery page) and fails validation when the block drifts.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

BEGIN = "// >>> RANDOM_ARCHIVE_PAGES (generated by tools/sync_random_archive.py — do not edit)"
END = "// <<< RANDOM_ARCHIVE_PAGES"
BLOCK_RE = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)


def routes_for(root: Path) -> list[str]:
    routes = []
    for path in sorted(root.rglob("*.html")):
        rel = path.relative_to(root).as_posix()
        if rel.endswith("404.html"):
            continue
        routes.append(rel)
    return routes


def render_block(routes: list[str]) -> str:
    items = ",\n    ".join(json.dumps(route) for route in routes)
    return f"{BEGIN}\n  const RANDOM_ARCHIVE_PAGES = [\n    {items}\n  ];\n{END}"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Synchronize or verify the Random Archive route list in wiki.js."
    )
    parser.add_argument(
        "root", nargs="?", type=Path, default=Path("docs"), help="public root (default: docs)"
    )
    parser.add_argument(
        "--write", action="store_true", help="rewrite the generated block instead of only checking"
    )
    args = parser.parse_args()

    root = args.root.resolve()
    if not root.is_dir():
        print(f"error: public root does not exist: {root}")
        return 2

    js_path = root / "assets" / "js" / "wiki.js"
    if not js_path.is_file():
        print(f"error: {js_path} not found")
        return 2

    text = js_path.read_text(encoding="utf-8")
    matches = list(BLOCK_RE.finditer(text))
    if len(matches) != 1:
        print(f"FAIL: expected exactly one generated route block, found {len(matches)}")
        return 1

    routes = routes_for(root)
    expected = render_block(routes)

    if matches[0].group(0) != expected:
        if not args.write:
            print(
                f"FAIL: Random Archive route list is stale "
                f"({len(routes)} routes expected); run with --write"
            )
            return 1
        text = text[: matches[0].start()] + expected + text[matches[0].end() :]
        js_path.write_text(text, encoding="utf-8")
        print(f"Synchronized Random Archive route list: {len(routes)} routes")

    print(f"PASS: Random Archive route list matches {len(routes)} public routes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
