import os

WIKI_DIR = "/home/user/01_Somnarak_Wiki"

mechanics_data = {
    "han-energy-and-damage.html": (
        "Han Energy & Damage Types",
        "Pugnahan, Ferrehan, Flerehan, Viderehan Physics",
        "#ef5b55",
        "banner_mechanics.svg",
        """
        <h2>1. The Four Damage Affinities</h2>
        <p>All offensive and defensive interactions in Somnarak are governed by the four elemental frequencies of refined Han energy. Each type targets a distinct structural or psychological layer of an operative or Sorrow Entity:</p>

        <div class="table-wrap">
          <table class="data-table">
            <thead>
              <tr><th>Damage Class</th><th>Color / Han Spectrum</th><th>Target Domain</th><th>Tactical Effect</th></tr>
            </thead>
            <tbody>
              <tr><td><strong>Pugnahan (권한 — 拳恨)</strong></td><td>Crimson Red (`#ef5b55`)</td><td>Physical Flesh &amp; Material Hull</td><td>Inflicts kinetic trauma, internal hemorrhage, and armor fracture.</td></tr>
              <tr><td><strong>Ferrehan (철한 — 鐵恨)</strong></td><td>Deep Cyan / Azure (`#38bdf8`)</td><td>Neural Coherence &amp; Composure</td><td>Drains Mental SP, induces paranoia, panic states, and hallucination.</td></tr>
              <tr><td><strong>Flerehan (비한 — 悲恨)</strong></td><td>Amber Gold (`#e6c94d`)</td><td>Composite Physical + Mental</td><td>Attacks physical health and mental composure simultaneously.</td></tr>
              <tr><td><strong>Viderehan (시한 — 視恨)</strong></td><td>Pale Platinum (`#f8fafc`)</td><td>Metaphysical Soul &amp; True Being</td><td>Deals true percentage damage; completely ignores standard armor defense.</td></tr>
            </tbody>
          </table>
        </div>

        <h2>2. Resonance Clashing Mechanics</h2>
        <p>When two opposing Han strikes collide in combat, a <strong>Resonance Clash (공명 격돌)</strong> occurs. Clash resolution is determined by three variables:</p>
        <ul>
          <li><strong>Base Skill Potency:</strong> The fundamental output generated by the operative's M.A.W. weapon.</li>
          <li><strong>Emotional Frequency Match:</strong> Bonus dice rolls granted when attacking an entity with its polar opposite sorrow element.</li>
          <li><strong>Stagger Multiplier:</strong> Winning consecutive clashes builds Stagger Gauge on the target, culminating in complete vulnerability.</li>
        </ul>
        """
    ),
    "maw-equipment-system.html": (
        "M.A.W. Equipment System",
        "Materialized Agony Wear: Weapons, Suits, and Gifts",
        "#e6c94d",
        "weapon.svg",
        """
        <h2>1. Architecture of Materialized Agony Wear</h2>
        <p><strong>M.A.W. (Materialized Agony Wear — 苦痛具現裝備)</strong> represents the pinnacle of Reverie Directorate military engineering. Rather than utilizing conventional projectile or combustion armaments, M.A.W. gear is woven directly from the crystallized emotional mass of contained Sorrow Entities.</p>

        <h2>2. Equipment Slots &amp; Risk Classifications</h2>
        <div class="table-wrap">
          <table class="data-table">
            <thead>
              <tr><th>Gear Slot</th><th>Primary Function</th><th>Risk Tiers</th></tr>
            </thead>
            <tbody>
              <tr><td><strong>M.A.W. Weapon (무기)</strong></td><td>Channels offensive Han into elemental blades, bludgeons, lenses, or scythes.</td><td>ZAYIN · TETH · HE · WAW · ALEPH</td></tr>
              <tr><td><strong>M.A.W. Suit (방호복)</strong></td><td>Provides multi-spectrum defense multipliers against the four Han damage types.</td><td>ZAYIN · TETH · HE · WAW · ALEPH</td></tr>
              <tr><td><strong>M.A.W. Gift (선물)</strong></td><td>Passive physiological relic grafted onto the operative's face, torso, or hands.</td><td>Innate manifestation upon high work resonance.</td></tr>
            </tbody>
          </table>
        </div>

        <h2>3. Set Resonance Bonuses</h2>
        <p>Equipping a complete three-piece M.A.W. set (e.g. <em>Named Vigil</em> from SE-001 or <em>Absolute Set</em> from SE-010) activates <strong>Harmonic Resonance</strong>, unlocking exclusive combat skills, emergency barrier shields, and permanent panic resistance.</p>
        """
    ),
    "containment-and-suppression.html": (
        "Containment & Suppression",
        "Work Types, Qliphoth Counters, and Breach Suppression",
        "#6f7ee8",
        "floor-2-maw.svg",
        """
        <h2>1. The Science of Anomaly Observation</h2>
        <p>Sorrow Entities cannot be destroyed by conventional physical force. Instead, the Hand of Change manages entities within reinforced isolation containment units using four calibrated work protocols:</p>

        <h2>2. The Four Work Orders</h2>
        <div class="table-wrap">
          <table class="data-table">
            <thead>
              <tr><th>Work Order</th><th>Primary Focus</th><th>Success Factor</th></tr>
            </thead>
            <tbody>
              <tr><td><strong>Instinct (본능)</strong></td><td>Physiological stabilization, bio-sap feeding, ambient temperature regulation.</td><td>High Fortitude</td></tr>
              <tr><td><strong>Insight (통찰)</strong></td><td>Environmental hygiene, crystal pruning, containment unit repair.</td><td>High Prudence</td></tr>
              <tr><td><strong>Attachment (애착)</strong></td><td>Social dialogue, emotional resonance synchronization, memory sharing.</td><td>High Temperance</td></tr>
              <tr><td><strong>Repression (억압)</strong></td><td>Psychic dampening, structural confinement, ego restriction.</td><td>High Justice</td></tr>
            </tbody>
          </table>
        </div>

        <h2>3. Qliphoth &amp; Sorrow Breach Counters</h2>
        <p>Each containment cell possesses a <strong>Sorrow Counter</strong>. Performing work orders with mismatched affinities or failing successive resonance rolls decrements the counter. When the counter hits zero, a <strong>Containment Breach</strong> occurs, requiring immediate deployment of floor suppression teams.</p>
        """
    ),
    "fracture-and-therapy.html": (
        "Fracture & Therapy Protocols",
        "Composure, Panic Types, and Echo Calibration",
        "#f0a6c4",
        "fracture.svg",
        """
        <h2>1. The Dynamics of Psychological Fracture</h2>
        <p>When an operative's Mental Composure (SP) is completely depleted by Ferrehan damage or witnessing horrifying entity manifestations, the operative enters a state of <strong>Fracture (균열 — Gunyeol)</strong>.</p>

        <h2>2. Four Clinical Panic Classifications</h2>
        <div class="table-wrap">
          <table class="data-table">
            <thead>
              <tr><th>Panic Classification</th><th>Behavioral Manifestation</th><th>Suppression Method</th></tr>
            </thead>
            <tbody>
              <tr><td><strong>Berserk (광란)</strong></td><td>Indiscriminately attacks allies and containment doors with enhanced kinetic strength.</td><td>Ferrehan (Mental) calming strike.</td></tr>
              <tr><td><strong>Panic Flight (도주)</strong></td><td>Flees uncontrollably across facility corridors, unlocking containment cells in hysteria.</td><td>Pugnahan (Physical) non-lethal pin.</td></tr>
              <tr><td><strong>Catatonia (혼수)</strong></td><td>Collapses into vegetative weeping; completely unresponsive to orders.</td><td>Medicinal Alpha Sap stimulant.</td></tr>
              <tr><td><strong>Self-Erosion (자해)</strong></td><td>Attempts self-termination under the psychic influence of the attacking entity.</td><td>Immediate sedative intervention.</td></tr>
            </tbody>
          </table>
        </div>

        <h2>3. Infirmary &amp; Echo Calibration</h2>
        <p>Fractured operatives are evacuated to the Floor 1 and Floor 4 Medical Infirmaries for <strong>Echo Calibration</strong>, where resonant tuning forks re-align the brain's emotional frequency to baseline stability.</p>
        """
    )
}

hub_html = """<!doctype html>
<html lang="en" data-article-status="curated">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Battle &amp; Systems Mechanics — Somnarak Wiki</title>
  <meta name="description" content="Technical systems directory for Somnarak: Han physics, damage matrices, M.A.W. equipment, containment protocols, and therapy.">
  <link rel="icon" type="image/svg+xml" href="../assets/icons/somnarak_icon.svg">
  <link rel="stylesheet" href="../assets/css/wiki.css">
  <script defer src="../assets/js/wiki.js"></script>
</head>
<body>
<header class="utility">
  <button class="nav-open" type="button" aria-label="Open navigation">☰</button>
  <a class="utility-brand" href="../index.html">SOMNARAK.WIKI</a>
  <span>YEAR 4,238 · DAWN INITIATIVE</span>
  <nav>
    <a href="../index.html">Main page</a>
    <a href="../characters/index.html">Characters</a>
    <a href="../lore/index.html">Lore</a>
    <a href="../factions/index.html">Factions</a>
    <a href="../entities/index.html">Sorrow Entities</a>
    <a href="../maw/index.html">M.A.W.</a>
  </nav>
  <div class="search">
    <input id="search" data-index="../data/search.json" aria-label="Search" placeholder="Search Somnarak Wiki">
    <div id="results"></div>
  </div>
</header>

<div class="wiki-shell">
  <aside class="left-rail">
    <div class="site-mark">
      <a href="../index.html">
        <img src="../assets/icons/somnarak_icon.svg" alt="Somnarak">
        <b>SOMNARAK</b>
        <span>WIKI ARCHIVE</span>
      </a>
    </div>
    <nav class="left-links" aria-label="Wiki navigation">
      <section>
        <h2>Archive</h2>
        <a href="../index.html">Main page</a>
        <a href="../characters/index.html">Characters Hub</a>
        <a href="../lore/index.html">Lore &amp; Cosmology</a>
        <a href="../factions/index.html">Factions &amp; Guilds</a>
        <a href="../departments/index.html">Hand of Change</a>
        <a href="../locations/index.html">Atlas &amp; Maps</a>
        <a href="index.html" style="color:#fff;font-weight:bold;">Battle &amp; Systems</a>
        <a href="../entities/index.html">Sorrow Entities</a>
        <a href="../maw/index.html">M.A.W. Codex</a>
      </section>
      <section>
        <h2>Echo-Cores</h2>
        <a href="../characters/the-director-majin.html">Majin (Director)</a>
        <a href="../characters/the-secretary-seiyon.html">Seiyon (Secretary)</a>
        <a href="../characters/the-containment-lead-dekan.html">Dekan (Containment)</a>
        <a href="../characters/the-extraction-lead-zyrak.html">Zyrak (Extraction)</a>
        <a href="../characters/the-research-lead-ayshuk.html">Ayshuk (Research)</a>
        <a href="../characters/the-border-lead-mellda.html">Mellda (Border)</a>
        <a href="../characters/the-archive-lead-marjuk.html">Marjuk (Archive)</a>
        <a href="../characters/the-outsider-ishall.html">Ishall (Outsider)</a>
        <a href="../characters/the-exile-xyan.html">Xyan (Exile)</a>
      </section>
    </nav>
  </aside>

  <main id="content">
    <div class="page-tabs">
      <span>Technical Manual</span>
      <b>SYSTEMS &amp; MECHANICS // 系統指南</b>
    </div>
    <div class="breadcrumbs">
      <a href="../index.html">Main page</a><i>›</i>Mechanics
    </div>

    <section class="department-hero" style="--floor:#e6c94d">
      <img src="../assets/icons/banner_mechanics.svg" alt="">
      <div>
        <span>REVERIE DIRECTORATE // TECHNICAL MANUAL</span>
        <h1>Battle &amp; Systems Mechanics</h1>
        <p>Han Damage Matrix, M.A.W. Synthesis, Containment Work Orders, and Psychological Therapy</p>
      </div>
    </section>

    <article class="article-body">
      <h2>Operational Systems Portals</h2>
      <div class="archive-portal-grid">
        <a class="archive-portal" href="han-energy-and-damage.html" style="--portal:#ef5b55">
          <span>DAMAGE MATRIX</span>
          <img src="../assets/icons/banner_grudge.svg" alt="">
          <b>HAN ENERGY &amp; DAMAGE</b>
          <small>Pugnahan, Ferrehan, Flerehan, Viderehan</small>
        </a>

        <a class="archive-portal" href="maw-equipment-system.html" style="--portal:#e6c94d">
          <span>ARMORY SYSTEM</span>
          <img src="../assets/icons/weapon.svg" alt="">
          <b>M.A.W. EQUIPMENT</b>
          <small>Weapons, Suits, and Gifts</small>
        </a>

        <a class="archive-portal" href="containment-and-suppression.html" style="--portal:#6f7ee8">
          <span>WORK ORDERS</span>
          <img src="../assets/icons/floor-2-maw.svg" alt="">
          <b>CONTAINMENT &amp; WORK</b>
          <small>Instinct, Insight, Attachment, Repression</small>
        </a>

        <a class="archive-portal" href="fracture-and-therapy.html" style="--portal:#f0a6c4">
          <span>PSYCHOLOGICAL</span>
          <img src="../assets/icons/fracture.svg" alt="">
          <b>FRACTURE &amp; THERAPY</b>
          <small>Composure, Panic, and Calibration</small>
        </a>
      </div>
    </article>
  </main>

  <aside class="floor-rail" aria-label="Hand of Change departments">
    <h2>HAND OF CHANGE</h2>
    <a class="floor-button f1" href="../departments/floor-1-neutral-command.html" style="--floor:#ef5b55"><span><small>FLOOR 1</small>NEUTRAL</span><img src="../assets/layout/hand/icons/icon_dept_f1_neutral.svg" alt=""></a>
    <a class="floor-button f2" href="../departments/floor-2-maws-keep.html" style="--floor:#6f7ee8"><span><small>FLOOR 2</small>MAW’S KEEP</span><img src="../assets/layout/hand/icons/icon_dept_f2_maws_keep.svg" alt=""></a>
    <a class="floor-button f3" href="../departments/floor-3-extraction-hall.html" style="--floor:#e6c94d"><span><small>FLOOR 3</small>EXTRACTION HALL</span><img src="../assets/layout/hand/icons/icon_dept_f3_extraction.svg" alt=""></a>
    <a class="floor-button f4" href="../departments/floor-4-insight-forge.html" style="--floor:#47c978"><span><small>FLOOR 4</small>INSIGHT FORGE</span><img src="../assets/layout/hand/icons/icon_dept_f4_insight_forge.svg" alt=""></a>
    <a class="floor-button f5" href="../departments/floor-5-border-watch.html" style="--floor:#d7d7d7"><span><small>FLOOR 5</small>BORDER WATCH</span><img src="../assets/layout/hand/icons/icon_dept_f5_border_watch.svg" alt=""></a>
    <a class="floor-button f6" href="../departments/floor-6-deep-vault.html" style="--floor:#8d2e42"><span><small>FLOOR 6</small>DEEP VAULT</span><img src="../assets/layout/hand/icons/icon_dept_f6_deep_vault.svg" alt=""></a>
    <a class="floor-button f7" href="../departments/floor-7-shadow-corps.html" style="--floor:#f0a6c4"><span><small>FLOOR 7</small>SHADOW CORPS</span><img src="../assets/layout/hand/icons/icon_dept_f7_shadow_corps.svg" alt=""></a>
    <a class="floor-button f8" href="../departments/floor-8-gate-watch.html" style="--floor:#f4efa0"><span><small>FLOOR 8</small>GATE WATCH</span><img src="../assets/layout/hand/icons/icon_dept_f8_gate_watch.svg" alt=""></a>
    <a class="rail-action" href="../departments/index.html">OPEN FACILITY DIRECTORY</a>
  </aside>
</div>

<footer>
  <div><b>SOMNARAK WIKI</b><br>Encyclopedia of the City of Unresolved Sorrow</div>
  <div>Current record: Year 4,238 · Dawn Initiative</div>
  <div>The Cycle has ended.<br>Xyan is home and commands Gate Watch.</div>
</footer>
</body>
</html>
"""

for fname, (title, sub, color, icon, body) in mechanics_data.items():
    page_html = f"""<!doctype html>
<html lang="en" data-article-status="curated">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>{title} — Somnarak Wiki</title>
  <meta name="description" content="Technical manual for {title}: {sub}.">
  <link rel="icon" type="image/svg+xml" href="../assets/icons/somnarak_icon.svg">
  <link rel="stylesheet" href="../assets/css/wiki.css">
  <script defer src="../assets/js/wiki.js"></script>
</head>
<body>
<header class="utility">
  <button class="nav-open" type="button" aria-label="Open navigation">☰</button>
  <a class="utility-brand" href="../index.html">SOMNARAK.WIKI</a>
  <span>YEAR 4,238 · DAWN INITIATIVE</span>
  <nav>
    <a href="../index.html">Main page</a>
    <a href="../characters/index.html">Characters</a>
    <a href="../lore/index.html">Lore</a>
    <a href="../factions/index.html">Factions</a>
    <a href="../entities/index.html">Sorrow Entities</a>
    <a href="../maw/index.html">M.A.W.</a>
  </nav>
  <div class="search">
    <input id="search" data-index="../data/search.json" aria-label="Search" placeholder="Search Somnarak Wiki">
    <div id="results"></div>
  </div>
</header>

<div class="wiki-shell">
  <aside class="left-rail">
    <div class="site-mark">
      <a href="../index.html">
        <img src="../assets/icons/somnarak_icon.svg" alt="Somnarak">
        <b>SOMNARAK</b>
        <span>WIKI ARCHIVE</span>
      </a>
    </div>
    <nav class="left-links" aria-label="Wiki navigation">
      <section>
        <h2>Archive</h2>
        <a href="../index.html">Main page</a>
        <a href="../characters/index.html">Characters Hub</a>
        <a href="../lore/index.html">Lore &amp; Cosmology</a>
        <a href="../factions/index.html">Factions &amp; Guilds</a>
        <a href="../departments/index.html">Hand of Change</a>
        <a href="../locations/index.html">Atlas &amp; Maps</a>
        <a href="index.html" style="color:#fff;font-weight:bold;">Battle &amp; Systems</a>
        <a href="../entities/index.html">Sorrow Entities</a>
        <a href="../maw/index.html">M.A.W. Codex</a>
      </section>
      <section>
        <h2>Echo-Cores</h2>
        <a href="../characters/the-director-majin.html">Majin (Director)</a>
        <a href="../characters/the-secretary-seiyon.html">Seiyon (Secretary)</a>
        <a href="../characters/the-containment-lead-dekan.html">Dekan (Containment)</a>
        <a href="../characters/the-extraction-lead-zyrak.html">Zyrak (Extraction)</a>
        <a href="../characters/the-research-lead-ayshuk.html">Ayshuk (Research)</a>
        <a href="../characters/the-border-lead-mellda.html">Mellda (Border)</a>
        <a href="../characters/the-archive-lead-marjuk.html">Marjuk (Archive)</a>
        <a href="../characters/the-outsider-ishall.html">Ishall (Outsider)</a>
        <a href="../characters/the-exile-xyan.html">Xyan (Exile)</a>
      </section>
    </nav>
  </aside>

  <main id="content">
    <div class="page-tabs">
      <span>Technical Guide</span>
      <b>SYSTEM SPECIFICATION // 系統規範</b>
    </div>
    <div class="breadcrumbs">
      <a href="../index.html">Main page</a><i>›</i><a href="index.html">Mechanics</a><i>›</i>{title}
    </div>

    <section class="department-hero" style="--floor:{color}">
      <img src="../assets/icons/{icon}" alt="">
      <div>
        <span>REVERIE DIRECTORATE // TECHNICAL MANUAL</span>
        <h1>{title}</h1>
        <p>{sub}</p>
      </div>
    </section>

    <div class="entity-meta-grid" style="margin: 20px 0;">
      <div class="meta-card">
        <b>SYSTEM TOPIC</b>
        <span>{title}</span>
      </div>
      <div class="meta-card">
        <b>AUTHORITY</b>
        <span>Reverie Directorate Research Corps</span>
      </div>
      <div class="meta-card">
        <b>APPLICATION</b>
        <span>Containment &amp; Combat Suppression</span>
      </div>
      <div class="meta-card">
        <b>CLASSIFICATION</b>
        <span>Curated Canonical System</span>
      </div>
    </div>

    <article class="article-body">
      {body}
    </article>
  </main>

  <aside class="floor-rail" aria-label="Hand of Change departments">
    <h2>HAND OF CHANGE</h2>
    <a class="floor-button f1" href="../departments/floor-1-neutral-command.html" style="--floor:#ef5b55"><span><small>FLOOR 1</small>NEUTRAL</span><img src="../assets/layout/hand/icons/icon_dept_f1_neutral.svg" alt=""></a>
    <a class="floor-button f2" href="../departments/floor-2-maws-keep.html" style="--floor:#6f7ee8"><span><small>FLOOR 2</small>MAW’S KEEP</span><img src="../assets/layout/hand/icons/icon_dept_f2_maws_keep.svg" alt=""></a>
    <a class="floor-button f3" href="../departments/floor-3-extraction-hall.html" style="--floor:#e6c94d"><span><small>FLOOR 3</small>EXTRACTION HALL</span><img src="../assets/layout/hand/icons/icon_dept_f3_extraction.svg" alt=""></a>
    <a class="floor-button f4" href="../departments/floor-4-insight-forge.html" style="--floor:#47c978"><span><small>FLOOR 4</small>INSIGHT FORGE</span><img src="../assets/layout/hand/icons/icon_dept_f4_insight_forge.svg" alt=""></a>
    <a class="floor-button f5" href="../departments/floor-5-border-watch.html" style="--floor:#d7d7d7"><span><small>FLOOR 5</small>BORDER WATCH</span><img src="../assets/layout/hand/icons/icon_dept_f5_border_watch.svg" alt=""></a>
    <a class="floor-button f6" href="../departments/floor-6-deep-vault.html" style="--floor:#8d2e42"><span><small>FLOOR 6</small>DEEP VAULT</span><img src="../assets/layout/hand/icons/icon_dept_f6_deep_vault.svg" alt=""></a>
    <a class="floor-button f7" href="../departments/floor-7-shadow-corps.html" style="--floor:#f0a6c4"><span><small>FLOOR 7</small>SHADOW CORPS</span><img src="../assets/layout/hand/icons/icon_dept_f7_shadow_corps.svg" alt=""></a>
    <a class="floor-button f8" href="../departments/floor-8-gate-watch.html" style="--floor:#f4efa0"><span><small>FLOOR 8</small>GATE WATCH</span><img src="../assets/layout/hand/icons/icon_dept_f8_gate_watch.svg" alt=""></a>
    <a class="rail-action" href="../departments/index.html">OPEN FACILITY DIRECTORY</a>
  </aside>
</div>

<footer>
  <div><b>SOMNARAK WIKI</b><br>Encyclopedia of the City of Unresolved Sorrow</div>
  <div>Current record: Year 4,238 · Dawn Initiative</div>
  <div>The Cycle has ended.<br>Xyan is home and commands Gate Watch.</div>
</footer>
</body>
</html>
"""
    with open(os.path.join(WIKI_DIR, "mechanics", fname), "w", encoding="utf-8") as f:
        f.write(page_html)

with open(os.path.join(WIKI_DIR, "mechanics", "index.html"), "w", encoding="utf-8") as f:
    f.write(hub_html)

print("All 5 Mechanics technical guides successfully generated!")
